### ISSUE TITLE
Transfer issues to topotoolbox3 repository

### ISSUE THREAD

**Issue by wkearn** [TopoToolbox/topotoolbox#7]
@wschwanghart: Can you let me know which of the issues in this repository 1) are still open issues that have not been resolved 2) are relevant to TopoToolbox 3 and 3) are not planned to be changed in TopoToolbox 2? 

I will transfer those issues to TopoToolbox/topotoolbox3 so we can keep track of them over there.

**Comment by wschwanghart** [comment]
You are right, these issues have partly been resolved in TT3, but still remain in TT2. 
#6 has largely been resolved, but not yet fully
#4 is resolved in TT3 using the functionalities of bwboundaries. However, the new approach, while being much better in handling more complicated polygons (holes and multipart), is much slower than the previous version. Hence, GRIDobj2polygon exists as before, and the new functionalities have been implemented in a new function GRIDobj2geotable.
#5 is not yet implmented and could be a good multi-purpose object in TT3 which is not too difficult to implement.
#3 has not been implemented, but there is a new STREAMobj2geotable function. The function converts a STREAMobj to a geotable which can be written as a shapefile. Hence, the following code does the trick:
```
GT = STREAMobj2geotable(S, ...);
shapewrite(GT,'file.shp')
```
Whether we really want a function that wraps these two lines, I don't know. Shapefile conversion, however, has been often asked for by users.
#1 and #2 are now implemented in TT3.

**Comment by wkearn** [comment]
I did not use GitHub's "Transfer issue" functionality so that these issues would stay open here as well, but I opened new issues:

- #6 => TopoToolbox/topotoolbox3#5
- #5 => TopoToolbox/topotoolbox3#6
- #3 => TopoToolbox/topotoolbox3#7

I did not copy #1 #2 or #4.
